import * as dotenv from 'dotenv';
import {
  app,
  BrowserWindow,
  ipcMain,
} from 'electron';
import * as path from 'path';

import { instruct } from './pplai';

let mainWindow: Electron.BrowserWindow | null = null;
dotenv.config();

function createWindow() {
    mainWindow = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
            preload: path.join(__dirname, 'preload.js')
        }
    });

    // Load the HTML file generated by Webpack
    mainWindow.loadURL(`file://${path.join(__dirname, "index.html")}`);

    mainWindow.on("closed", () => {
        mainWindow = null;
    });
}

ipcMain.handle('instruct', async (_event, instruction: string) => {
    return instruct(instruction);
});

app.on("ready", createWindow);

app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
        app.quit();
    }
});

app.on("activate", () => {
    if (mainWindow === null) {
        createWindow();
    }
});
